<h1>Users</h1>

</br>


<p>
    <a href="<?php echo $this->url('sonuser-admin', array('action' => 'new')); ?>">Novo</a>
</p>
<table class="table">
    <tr>
        <th>Id</th>
        <th>Nome</th>
        <th>Email</th>
        <th>Ação</th>
    </tr>
    
    <?php foreach ($this->data as $entity): ?>
        <tr>
            <td><?php echo $entity->getId(); ?> </td>
            <td><?php echo $entity->getNome(); ?> </td>
            <td><?php echo $entity->getEmail(); ?> </td>
            <td></td>
        </tr>
    <?php endforeach; ?>
    
    
</table>

